### ISSUE TITLE
All settings gone.

### ISSUE THREAD

**Issue by My1** [mailvelope/mailvelope#294] opened 2015-03-15 21:44 UTC
I know there's already an issue about that but that was 6 "main-beta" versions and 2 years ago so I make a new one
with version 0.12.1 I seem to lose my setting already happened twice (or maybe even more often)

Please do something about this bug...

**Comment by hcderaad** [comment] 2015-08-22 19:45
I also experience the "all settings gone" issue on FF 40 on openSUSE. It happens every couple of restarts of the browser. If there is anything I can do to test, please let me know.

**Comment by hcderaad** [comment] 2015-08-31 09:51
Probably related to #304

**Comment by toberndo** [comment] 2016-12-06 16:31
Duplicate of #304. Closing as 304 has more details.

**Closed by toberndo** 2016-12-06 16:31 UTC
