### ISSUE TITLE
Cannot open Options when Firefox private browsing mode is enabled

### ISSUE THREAD

**Issue by ricola** [mailvelope/mailvelope#504] opened 2017-04-01 09:45 UTC
* When I'm running Tor Browser 6.5.1 based on Firefox 45.8.0 which uses the private browsing mode of Firefox by default.
* And I click on the Mailvelope icon and choose Options nothing happens.
* If I disable the private browsing mode from Menu → Preferences → Privacy → Always use private browsing mode, then I can get to the Options page.

The same thing happens in vanilla Firefox (and not Tor Browser).

**Comment by toberndo** [comment] 2017-10-09 13:44
Can't reproduce any more with Firefox 52 and 56 and Mailvelope v2.0.0.
Seems like this issue is fixed with Web Extensions.

**Closed by toberndo** 2017-10-09 13:44 UTC
