### ISSUE TITLE
Support secure PGP public key exchange via DNSSEC

### ISSUE THREAD

**Issue by renne** [mailvelope/mailvelope#412] opened 2016-08-07 09:13 UTC
Hi,

the big show-stopper in in email-end-to-end-encryption is the secure exchange of the public keys.
Yesterday the [IETF has published the new RFC 7929 - DNS-Based Authentication of Named Entities (DANE) Bindings for OpenPGP](https://tools.ietf.org/html/rfc7929).

The [IETF RFC 7929](https://tools.ietf.org/html/rfc7929) standardizes how to publish public OpenPGP-keys via DNSSEC-secured Openpgp DNS resource records. This simplifies the public key exchange and makes end-to-end-encryption usable for John Does. ;)

As browsers do not allow direct access to DNS I suggest to add some functions to the Mailvelope-API for [DANE-Openpgpkey](https://tools.ietf.org/html/rfc7929) look-ups.

The Pear-PHP library [Net_DNS2](https://github.com/mikepultz/netdns2) supports the look-up of OpenPGP DNS resource-records.

**Comment by pat247** [comment] 2016-08-07 19:41
>  Security is provided via Secure DNS, however the OPENPGPKEY
   record is not a replacement for verification of authenticity via the
   "web of trust" or manual verification. 

RFC 7929

**Comment by toberndo** [comment] 2016-08-08 09:31
Could be implemented in the Mailvelope key server: https://github.com/mailvelope/keyserver/issues/8

**Comment by rugk** [comment] 2016-09-08 21:12
Dupe of https://github.com/mailvelope/mailvelope/issues/290, is not it?
And also very much related to https://github.com/mailvelope/mailvelope/issues/319.

**Comment by renne** [comment] 2016-09-10 07:09
https://github.com/mailvelope/mailvelope/issues/290 wants to use TXT-Records while [IETF RFC 7929](https://tools.ietf.org/html/rfc7929) uses a new resource record type 'OpenPGPkey' (generic Type 61).

https://github.com/mailvelope/mailvelope/issues/319 seems to be about resolving hostnames of key-servers which are published via DNS-Robin-Round. This is not publishing/resolving OpenPGP-keys via DNS.

**Comment by toberndo** [comment] 2018-12-17 16:19
See also interesting discussion at https://github.com/openpgpjs/openpgpjs/issues/487
As we have now WKD support in Mailvelope v3.0, there are no further plans to add key discovery via DNS.

**Closed by toberndo** 2018-12-17 16:19 UTC
Labels: Key Server
