### ISSUE TITLE
Error! Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by johnrandomsmith2** [mailvelope/mailvelope#251] opened 2014-12-03 00:41 UTC
Sent myself an encrypted attachment from thunderbird. Got the subject line error in google chrome on a chromebook

Google Chrome   38.0.2125.110 (Official Build 96936e9) 
Platform    6158.70.0 (Official Build) stable-channel peppy
Blink   537.36 (@1493aa5)
JavaScript  V8 3.28.71.17
Flash   15.0.0.189-r2

Below is from the console

locked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set. about:blank:1
338Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (min-resolution: 144dpi), (-webkit-min-device-pixel-ratio: 1.5) rs=AItRSTMjvjBuFCWMQf1lpxfy73aR-jGPAA:243
Failed to load resource: net::ERR_CACHE_MISS https://mail.google.com/mail/u/0/?pli=1#inbox/14a0d7327dfe85a7
Failed to load resource: net::ERR_CACHE_MISS https://talkgadget.google.com/u/0/talkgadget/_/chat?client=sm&prop=gmail&na…leh=380&mmoleh=36&two=https%3A%2F%2Fmail.google.com&host=1&zx=7wc8qfuqfipn
Failed to load resource: net::ERR_CACHE_MISS https://apis.google.com/u/0/_/streamwidgets/hovercard?origin=https%3A%2F%2F…nderstart&id=I1_1417565901204&parent=https%3A%2F%2Fmail.google.com&pfname=
Denying load of chrome-extension://kajibbejlbohfaggdiogboambcijhkke/common/dep/bootstrap/css/bootstrap.css.map. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension. ?pli=1:1

**Comment by toberndo** [comment] 2016-12-06 16:07
This is either related to missing bzip2 compression in OpenPGP.js which we track in https://github.com/mailvelope/mailvelope/issues/8.
Or could be already fixed in OpenPGP.js as we have seen many improvements in the library since reporting this issue. Please re-open if possible to reproduce with latest Mailvelope.

**Closed by toberndo** 2016-12-06 16:07 UTC
