### ISSUE TITLE
Support for PGP and smartcard/yubikey

### ISSUE THREAD

**Issue by slowz3r** [mailvelope/mailvelope#432] opened 2016-10-06 15:06 UTC
As it currently sits you cannot decrypt messages using a key generated for use on a smart card/yubikey.  The way it sits right now, instead of looking for the smartcard/yubikey and prompting for the pin of the card/key it asks for the key passphrase.  This generates an error saying invalid enum value or something to that effect.

Please consider adding this feature as it would greatly enhance the security of Mailvelope and PGP messages.

**Comment by runasand** [comment] 2016-10-07 14:39
See also https://github.com/mailvelope/mailvelope/issues/343 and https://github.com/mailvelope/mailvelope/issues/238 for existing tickets requesting this feature.

**Comment by toberndo** [comment] 2017-03-20 11:40
Closing as duplicate of #238

**Closed by toberndo** 2017-03-20 11:40 UTC
