### ISSUE TITLE
Beta WebExtension version doesn't work until page is reloaded

### ISSUE THREAD

**Issue by rvandermeulen** [mailvelope/mailvelope#534] opened 2017-09-03 17:19 UTC
I've been testing out the beta 1.9.2 webextension version with Firefox Nightly 57 and have noticed that with GMail at least, Mailvelope doesn't seem to properly detect encrypted emails until I reload the page. Subsequent operations work as expected.

**Comment by toberndo** [comment] 2017-09-05 08:41
Related to: https://bugzilla.mozilla.org/show_bug.cgi?id=1290016#c2

Really hard to reproduce on my side, this occurred more often with the first betas, thought it's fixed with https://github.com/mailvelope/mailvelope/commit/364f409ca74986960f40f279dc4b153cffc0989b but I can see that it still happens occasionally with FF57.

**Comment by toberndo** [comment] 2017-09-05 14:00
@rvandermeulen I applied now the changes as advised by https://bugzilla.mozilla.org/show_bug.cgi?id=1290016#c3
Could you please retest with: https://download.mailvelope.com/releases/v1.9.3b/

**Comment by rvandermeulen** [comment] 2017-09-06 13:31
Unfortunately, it appears to still be happening :(. In the browser console,
I'm seeing "this.widget is null ext-browserAction.js" errors, but it isn't
clear to me if those are actually being caused by Mailvelope or something
else.

this.widget is null ext-browserAction.js:523
    updateWindow chrome://browser/content/ext-browserAction.js:523:9
    build/< chrome://browser/content/ext-browserAction.js:231:40
    emit resource://gre/modules/ExtensionUtils.jsm:258:40
    handleEvent chrome://browser/content/ext-browser.js:133:7
    updateCurrentBrowser chrome://browser/content/tabbrowser.xml:1308:15
    onselect chrome://browser/content/browser.xul:1:44
    set_selectedIndex chrome://browser/content/tabbrowser.xml:8397:13
    set_selectedPanel chrome://global/content/bindings/tabbox.xml:694:13
    set_selectedIndex chrome://global/content/bindings/tabbox.xml:412:15
    set_selectedItem chrome://global/content/bindings/tabbox.xml:444:34
    _selectNewTab chrome://global/content/bindings/tabbox.xml:489:11
    onxblmousedown chrome://global/content/bindings/tabbox.xml:811:11

**Comment by mdik** [comment] 2017-09-06 13:59
@rvandermeulen is it only the very first time after installing and setting up Mailvelope, or each time you open the browser and go to gmail?

Because in the former case, I'd say mitigating through documentation (inside and outside the UI) would be good enough, if the latter it definitely needs fixing.

@toberndo What in general would be the best way to triage this?

**Comment by rvandermeulen** [comment] 2017-09-06 14:01
I've hit it multiple times after restarting the browser.

**Comment by mdik** [comment] 2017-09-06 14:04
:cry:

**Comment by toberndo** [comment] 2017-09-07 09:58
I created now a new version that uses browser.webNavigation.onCompleted instead of browser.webNavigation.onDOMContentLoaded which should give more time between page loading and content script injection. Also added more verbose error logging.

@rvandermeulen Just to be sure about the procedure:
- restart Firefox nightly
- open tab with Gmail
- open PGP email
-> Mailvelope does not detect
- reload tab
-> Mailvelope does detect

Is that correct?

If you could please retest with the following package. Best would be to open and clear the browser console before opening the Gmail tab and then sending the console output after you open Gmail.
Had to zip the xpi file as GitHub does not allow xpi uploads. Thanks!

[mailvelope-1.9.4-an+fx.xpi.zip](https://github.com/mailvelope/mailvelope/files/1284241/mailvelope-1.9.4-an.fx.xpi.zip)

**Comment by rvandermeulen** [comment] 2017-09-08 13:34
I was still able to reproduce with 1.9.4b. My situation is a bit different from your STR, however. I have two GMail pinned tabs (one work and one personal), so they open automatically on browser startup. All my encrypted mail comes in by way of my personal account, so that's the only GMail instance where I've been testing things to date.

One thing I'll try is forwarding an encrypted email to my other account to see if this state affects both tabs or just one when it's happening.

**Comment by rvandermeulen** [comment] 2017-09-08 13:56
Aha, we may be on to something here! Just got in that state again and sure enough, my first (work) pinned tab worked fine with the email I'd forwarded to it right off the bat, but my second (personal) pinned tab didn't work until I reloaded it.

**Comment by toberndo** [comment] 2017-09-09 09:59
> I have two GMail pinned tabs (one work and one personal), so they open automatically on browser startup.

@rvandermeulen That's really valuable information. I think there is a race condition with page load of the pinned tab and concurrent startup of Mailvelope. Should be fixed in the latest beta. If you could please do one more round of testing with: https://download.mailvelope.com/releases/v1.9.5b/
(Hopefully the last test required for this bug).

**Comment by rvandermeulen** [comment] 2017-09-11 12:44
This is looking really encouraging! I haven't been able to reproduce since
installing 1.9.5b a couple days ago.

On Sat, Sep 9, 2017 at 5:59 AM, Thomas Oberndörfer <notifications@github.com

**Comment by toberndo** [comment] 2017-09-11 12:52
I was hoping for that answer. Great! Thanks for testing so far.

**Comment by toberndo** [comment] 2017-09-12 13:03
Closing for now. See also https://download.mailvelope.com/releases/v1.9.6b/ which raises file size for file encryption to 50 MB.

**Closed by toberndo** 2017-09-12 13:03 UTC
