### ISSUE TITLE
Message encrypted for all key packets of a key fails to decrypt

### ISSUE THREAD

**Issue by gehwissenlos** [mailvelope/mailvelope#370] opened 2016-01-29 12:59 UTC
I want to decrypt a mail but I always get the message "Error decrypting message!" On my phone with APG app it works.

Here is the background.html message:
Error: Decryption failed due to missing MDC in combination with modern cipher.
    at SymmetricallyEncrypted.decrypt (openpgp.js:15431)
    at Message.decrypt (openpgp.js:11955)
    at openpgp.js:12393
    at openpgp.js:12538
    at execute (openpgp.js:12537)
    at Object.decryptMessage (openpgp.js:12392)
    at DedicatedWorkerGlobalScope.self.onmessage (dep/openpgp.worker.js:94)onError @ openpgp.js:12554

The console shows this when I close the error message:
Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

o.fn.extend.remove  @   cs-mailvelope.js:3
mvelo.DecryptFrame._removeDialog    @   cs-mailvelope.js:960
(anonymous function)    @   cs-mailvelope.js:978
target.(anonymous function) @   extensions::SafeBuiltins:19
EventImpl.dispatchToListener    @   extensions::event_bindings:387
target.(anonymous function) @   extensions::SafeBuiltins:19
publicClass.(anonymous function)    @   extensions::utils:94
EventImpl.dispatch_ @   extensions::event_bindings:371
EventImpl.dispatch  @   extensions::event_bindings:393
target.(anonymous function) @   extensions::SafeBuiltins:19
publicClass.(anonymous function)    @   extensions::utils:94
dispatchOnMessage   @   extensions::messaging:310

Browser: Google Chrome 48.0.2564.97 (Offizieller Build) m (64-Bit)

**Comment by toberndo** [comment] 2016-01-29 13:39
The combination of modern cipher and missing integrity protection has been deprecated in OpenPGP.js: https://github.com/openpgpjs/openpgpjs/pull/360#issue-110328005

It's a rare case and should be fixed on the sender side by using a modern PGP implementation.

**Comment by gehwissenlos** [comment] 2016-01-29 13:43
Thanks for your answer, toberndo.
So this is not a mailvelope/openpgp.js problem but a totemomail problem?

**Comment by toberndo** [comment] 2016-01-29 13:59
I think it should be fixed on their side, also GPG 2.1.9 will raise an error message in the default configuration if MDC is missing with new ciphers.

**Comment by meitar** [comment] 2016-02-27 11:15
I'm using [OpenPGP-PHP](https://github.com/singpolyma/openpgp-php/) to generate both keys and send ASCII-armored, encrypted messages in [a plugin](https://github.com/meitar/wp-pgp-encrypted-emails/) but unfortunately I've noticed that Mailvelope is unable to decrypt the message with this same error as described above.

In my case, I've tried using Firefox (44.0.2) with Mailvelope v1.3.6, and I'm seeing the following error in the browser console when the "Error decrypting message!" overlay appears:

```
[49]</d.prototype.decrypt@resource://jid1-aqqsmbyb0a8adg-at-jetpack/data/openpgp.min.js:7:6910
h/<@resource://jid1-aqqsmbyb0a8adg-at-jetpack/data/openpgp.min.js:7:11332
m/c<@resource://jid1-aqqsmbyb0a8adg-at-jetpack/data/openpgp.min.js:7:12637
m@resource://jid1-aqqsmbyb0a8adg-at-jetpack/data/openpgp.min.js:7:12607
h@resource://jid1-aqqsmbyb0a8adg-at-jetpack/data/openpgp.min.js:7:11310
[1]</self.onmessage@resource://jid1-aqqsmbyb0a8adg-at-jetpack/data/openpgp.worker.min.js:1:2353
 openpgp.min.js:7:12704
n()
```
Other OpenPGP clients (GnuPG and the MacGPG tools) are able to decrypt the same text without an issue.

In meitar/wp-pgp-encrypted-emails#9 there's some discussion about maybe this being caused by an incompatibility between OpenPGP-PHP and OpenPGP.js but I am not a PGP expert and do not know how to go about debugging this particular issue.

Is this something that needs to be fixed in OpenPGP-PHP, OpenPGP.js, Mailvelope, or somewhere else? Happy to provide more details if I can and if they'd be useful. Thanks.

**Comment by toberndo** [comment] 2016-03-01 17:31
@meitar according to https://github.com/meitar/wp-pgp-encrypted-emails/issues/9#issuecomment-189659883 this seems independent of the used key. Could you encrypt a message with [my key](http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x5D031F1D410B980FBC006E3202C134D079701934) and send me the message? Thanks.

**Comment by meitar** [comment] 2016-03-01 18:04
Hi Thomas,

Thanks for looking into this. Embedded in this email is the ASCII-armored output of a WordPress notification email generated by the WP PGP Encrypted Emails plugin that has been encrypted with your public key. The contents *should* decrypt to a clearsigned message with these contents:

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

A new comment on the post "hello world" is waiting for your approval
http://local.wordpress.dev/2016/02/19/hello-world/
Author: Meitar (IP: 192.168.50.1, 192.168.50.1)
Email: meitarm+github@gmail.com
URL: https://maymay.net/
Comment:
This is a test of an encrypted comment notification email sent from WordPress using the WP PGP Encrypted Emails plugin.
Approve it: http://local.wordpress.dev/wp-admin/comment.php?action=approve&c=176
Trash it: http://local.wordpress.dev/wp-admin/comment.php?action=trash&c=176
Spam it: http://local.wordpress.dev/wp-admin/comment.php?action=spam&c=176
Currently 123 comments are waiting for approval. Please visit the moderation panel:
http://local.wordpress.dev/wp-admin/edit-comments.php?comment_status=moderated

-----BEGIN PGP SIGNATURE-----

wv8AAAEkBAEBCAAY/wAAAAUCVtXYLP8AAAAJEKgqRS6Gb1VlAACIBQgAiAVWAuyTZHclRP59544
6HFH9M3FyzLXABwBStH7Du8q3D6GWGJi+w9ypTQTNf4VoK3kVTlM9LaIbh/Zjvk9ePRzA97fjw+
R1m7Ey9KFfRwygznOABLZW9xXkRzm1YtqW+fC4n5pMYH1IQmDYSZOr3IfB9fsNSrd3koFi6yqlU
KeA1H7K8pWtUHfgFrltFiJ52uW3NfvaDpS3LjW6d7e0WAsDze399FS3lh2NGCmrlRKdnpri7IuL
DXx5ufFWq5ErHGF8GZf6NewogYhLYZMAWVAghVsnSRJVjKpfAjVbOji56SHpcYs2AWInFMBZM5g
1M/iNzv4dP6Tk0dm/Hb0ZzQ==
=xL33
-----END PGP SIGNATURE-----

The public key you need to verify the signature is this one:

-----BEGIN PGP PUBLIC KEY BLOCK-----

xv8AAAENBFbNlVIBCAChB+WykpSIc7ZrdGKYkuOau0MPhrZWmZCjKxSTeq+4aMgu1G3qW938Luz
H3KxgbySsEYZeGGCBb0MxDpEb1g/IKqGGYfSTjjhjH4cpgSiDNy8zePhBQkTWKvRXvC7Yve3vGc
XVHOX6NJH98EZUALuVNBT3asKsFuqk398HzDZ9RnzdZuM5/1vIBCZTW/FlSw0xg5B3z739k0XT+
ama0fEcZiVW+f6dNpRgbZ5gzpKZ2vNyDjaVHIf5+5mB89QsbulZaclEBvFeIWvxWNd3WxTsXvop
OwIfdEYDT/NqA7l05cLezbODNsxDVOl1Ih54qa+j9AJbVcteW8nInUIkyVyvABEBAAHN/wAAACl
Xb3JkUHJlc3MgPHdvcmRwcmVzc0Bsb2NhbC53b3JkcHJlc3MuZGV2PsL/AAABLAQTAQgAIP8AAA
AFAlbNlVL/AAAAAxsBAv8AAAAJEKgqRS6Gb1VlAAAhAQf+IQFMYhvLUEyk71ANuKuL3Rm3IDGLZ
KedNV8c1BsovmTfgCfJeCNthnxr3/vXgt4vzs0XtRYLtg4aEpeq7lFMl08q4biNCR8eQ67FAfxr
AmGqi8JN93O4oyX0CpNCAiu+8tLGv2znn5jnhFz65Cwa3a5wu1sKsfVU91CqolOsFML25FgLCWR
9MEUeqUizAKksj+tHHwpeZJK5JfvlCpBQtI3DVHmptcu64FI5CZeicBIg8AqpjVW2u1wEsh1ZXW
1kz9jYSKZeEiwAqXz7JcUqq8EBrPAepqqGh9xaDMHmvvM5GwkdrPPVKv8S6jLE1rWuPmO0duDr8
f0/XxFXoGoILA==
=rJYU
-----END PGP PUBLIC KEY BLOCK——

The encrypted contents of the email that tools other than Mailvelope/OpenPGP.js is able to decrypt is as follows:

-----BEGIN PGP MESSAGE-----

wf8AAAIMAzCKKLdTMVbPAQ/9GwdEhIAbDvvvJ4K8jzGfs4/4+2tB3qUhZpvc9vmTAQOFDdge3Na
jBUEMQVu97dysvMSES65sSY32tgtjV1yMwwAB+wjRNpI/kRhlkTn5Yg8VOvLd6//Mz5q0ktIUhT
erg5qhEST24mcBJGIYlMZr+daPKjdnp5Ur4tJlYK1zYyzjDYf7MKxiBiOyshVY7TXQyH28oQgXe
Noc5tN/imHq8ruIeQOMBLvnL3AsIsimhYDu3F2bk1EbumT+uJoLAVfa/UKkzaGSNGEdyj2Uerc9
b/KxobrXUOL4i1wXwtVkZYxZTIggKDfEHWpb24VaJA21bvu+ClFrnF9AK3AlcV+saDjQgofsswl
XN63nDMRDHpOtPBzNbOgyoV4DGn3Z716z3+dXWVLi09ETbk3rpqsirmopacf8bD05c5/uxdpZDc
sRP+pkh6VTlOPArbZ+OUqkE2FH8qWpPXXFV45LMahz2p58eTBwVSUsDGSHAwpNGiHYmMcHmSTfp
77WTFV+SCTweSCpBq1zP5VLenhnp2f80wTX322pvKiveNlo54r4JBKk2o35vDW7bP/cNLB5Xz9/
FhxNd2SYTWPlTdpd8c3yQXlHdcESSBso9QKRHfkcv5+jZnQq/x9clkdeinTDhtlRm7JFOWqb0l8
jrBkeTaQbElIF5k7SieGla9ia1lEG3ODB/wAAAgwDAsE00HlwGTQBD/9uTtrrO7RhUqKU8FIXtU
03Jv+zdhItLozDkM8iypiphoX7WKhCQGBlouneQrdClRjHQvRiaH0qnld8ReinD+1wkbK5rP5k6
bsMS6AHED6RiWUEfQamaM9ixMarCu4TEyHm38Hr82B7ndJf5Kfp7y87WdLqiAWYsDQospGBGyF4
lTcXBLdB6r/363nDQkz6QjY1tvRo6RInN6LqW83b76UONU/xDSuWnb468CDPvWRp4Aa8C+KIe4f
nmJrU+JuWcIbAAOUwoJpbAuZGfKQwlKL71HGMi0oTNqfivDyDDREWm4HPTn2mKRZN/2n7eigTvv
E8jPOq5wUMch+IEerfnDhY/kffUYu2uvUjPrqTUU5ckoaCw0qJ8A7bfc1wlnad6eB8Xw01h4oSQ
qZ9nNrr1gTn/s5Rj9RbAPKWLVQX3H7gZS4oFGTUW3LeGhzkvgOiJhmrsyY3TG3aE0LJCX8us1/F
X3VomCFcbj2Gw3PtBMbHe4/6nPvoqt2AfEFI8bjuK0t9mGOxg0k53MN8YG+2HZdnSJfEwn/4Jle
pCvUqqTlBTBHTSGm+Leya/6EL/HrSmvoHJD/zIfL7hFwkgFI8Bte00N28Zpe2P/h5v6gKvBKzS6
4ryKJFBJVZZ1bQqw+DkCMM42M5Mn4q/xPrTxXNOQnXPFe56l6OzVTMOCBoF87cPNL/AAAFRQHeK
zLbttLNgluwjlJ3uU0vha/P9ak27TLSGgw6VvlABiMKzvclWxtoyPfyGWR9QPEsLwYSRaZ5lIq6
BkvVyGoIP9bQbZHOE/2evjl5wdWzU2/AE+kVOyLG4e+AhQCzGAJeLSaEcwDQ7cdhaAn8vjYOnQF
xo3EAo3haeUhQRo8nnZB6RLuardVxkO2+aHI5TNCdXmbpoGjC7o5g3fyC9Pmat/jkHjxjdnEdrI
TGICn+yknPdDJ29LsWPFd9TVpjN3IMUsSpUZlefoIC+/QhZVPHlXFshb1XQgHtJUvF/oSxPzy+1
RmOuM456gCJukpJqJ67MoEp5lblPQm9d274c8lDpYWWYrS6hwK75T8RQ7WCKvkkPgMQPmPnJ2Gq
xA+wEbCrizGC9/fNttli2+M2Sx7J42DyFnb5jdBszDxDQX1GDKz/PdJ/VPSWpJ05fyMBT1XvEs+
m4TWxGOWrPWpAHoiIvl/0Oh5nGuQ1VY/vBh35iqdkrjl5y+tq1rAlEbGXJnsGdmVbie3NE4lr0I
fxXpUQH48G2rJlXQsKVMpXvmHFiI+u13pIYZpsiYi557IZ/LSa03fAec4duwtUxMJprlWmfm2jh
/3ZcSbGFhk2+7m0MCGwDFkHzaAok68IlgtzatQPlxMaRD3ruLDveMVuuvxrdsY8hXMtAYChTMb9
0Gug5qf92ooW6Y+XTl4BExyBKtIRwrdle5sNhuC0ZeQVZFSWOQoTqkpVcHsi+Hnf4TfLsdBELKd
uRa3I73azig8hQdbkGs/0+e4+QLRrNPSwr00XNgXFTGFmf1oywEgdiPyxKZmv6ZrKOTeSq/sOkZ
LD79RRRkWFLhgL8Bjk2DVPCbVxhxpgGQi9X83p5JqE9FL6MEq2xbym6W2cdxJEurV946VFlCwji
qXau45g79zQICAfMRBEUYAn9n37cBZvMq3oz1vld4qtYQkWKCfiKy+DcKZ80DkZu+gcH5/6crSK
kQhWQytaJBMWklUajh1JQ5Ada65Vppy60LuHlNiy2nMRf0PM1PG5LGMZd6lZ9qy7y5p8Tj8j9Et
HFrS1kUHjWrLe9kictvRsqZIpPkxn4HrWHuupWjlP0d137IoGPB1rE16dOlMSqIHCZYcQEa848m
x6UCJn7fQEojN94Oapw8optZXB0SZ6xSyxdzDMbAXNmrLhqIxVb22HKrV8zDOYmrTSLX6g+W9Q3
GJLWKamBOG8DbkBsn0WKz40aeUEwf2gxE5cwjHYQTQMIAHyCSoUUTDZtreWmWoygQiNrQzzrRBj
8t7d3DSmjQTqwNo+f4AZFyUr6Fr5q6qs798LXmNnYqh0GyVsYbgaL5hk6xM6X2FI4NH0tL37qk9
wTPibFf7TAa+il572zFG4Qw09FRPVipdpMX3WVKOTzNuaA6AfGVV1GRZ/7Osa64WqJT80QJflLj
G62xJFoQWUUCJEgl6yZ96dBXoyJwzmC4dD+DlxysMTKuWRBdWBNYyxzeVUvJ31yMM/UTaN6IPOR
+4mZNUOzX1hCinkyrslDMNBF8lzZkU5qvtDqQygTuP0wgKukx860wHOHyGtpn6NPksYwpHdJo7D
G1kuAeSKAA6Gzo+sS0yPFPSz1rPeZGcU1FSoNL9XFmpgkIXZelHUEtkfu5Jb1LdhEWkSpvYZgts
r94D4OAX4RYp9bm/08ktgZj64pZ5HmsX/BXNj1BM/PyVTveqE2lPiBo6qDz5slVy+jY5Gg9U0Y3
CIV9hTTc/ZCUItN13Vu/VRv6Jd//MdVAXzv26CdqjjxSa6j2PIWCGUnWNr/SdmVZB6bB9w
=O5qU
-----END PGP MESSAGE-----

Thank you again for looking into this!
-Meitar
https://maymay.net/

**Comment by toberndo** [comment] 2016-03-01 19:10
Ok, thanks for the test messages. Could reproduce the problem in Mailvelope. OpenPGP-PHP unlike most other PGP implementations encrypts the message not only for one key paket of a given key, but for all key packets present on the key. This collides with the key caching mechanism in Mailvelope. Needs to be fixed on Mailvelope side.

**Comment by meitar** [comment] 2016-03-01 19:15
Thanks for looking at that so promptly! I admit I did not understand what this means, bit also don't technically need to since you say it needs to be fixed on Mailvelope side. Nevertheless, I'm interested. If you are willing, can you explain that to me like I'm five years old? :)

**Comment by toberndo** [comment] 2016-03-02 16:14
So PGP consist of a primary key and optionally multiple subkeys. If you want to encrypt with a key, implementations like OpenPGP.js (Mailvelope) or GPG choose one valid subkey and encrypt a message with this subkey. OpenPGP-PHP instead takes all available subkeys and the primary key and encrypts the message for all of them. If you unlock a key in Mailvelope with a password, for performance reasons, only a certain subkey is decrypted, exactly the one that is required to decrypt the message. Here comes the error in Mailvelope: a key consists of subkeys A and B, you look at message and see that A is required to decrypt, so you unlock A with the password. Hand over key and message to OpenPGP.js to decrypt, but then OpenPGP.js wants to decrypt the message with key B which is not unlocked and raises an error.

**Comment by meitar** [comment] 2016-03-02 16:55
So if I understand correctly, since OpenPGP-PHP encrypts messages with each and every subkey (packet) present in a given "public key" (i.e., `PGP PUBLIC KEY BLOCK` when ASCII-armored), since Mailvelope only unlocks one subkey but the message was encrypted to multiple subkeys, when Mailvelope passes control to OpenPGP.js, OpenPGP.js tries decrypting the message with *both* subkeys even though only one is required? Then, when OpenPGP.js encounters the still-locked subkey, it errors.

Assuming I got that right, then that was a fantastic explanation and made perfect sense. Thanks so much, @toberndo!

**Comment by toberndo** [comment] 2016-03-02 17:04
Almost correct.

> OpenPGP.js tries decrypting the message with both subkeys even though only one is required

It decrypts with only one subkey, but this might be the one that was not unlocked by Mailvelope.

**Comment by meitar** [comment] 2016-03-02 17:15
Ah, I see. So only in the case where OpenPGP.js *happens* to use the same subkey that Mailvelope unlocked does the decryption succeed? And this hasn't been a problem before because most OpenPGP implementations only encrypt with one subkey, rather than all of them, like OpenPGP-PHP does.

**Comment by toberndo** [comment] 2016-03-02 17:35
Yup

**Comment by meitar** [comment] 2016-03-02 23:47
Ah, got it. Thanks again for taking the time to explain that to me. :)

**Comment by toberndo** [comment] 2019-03-11 14:37
> If you unlock a key in Mailvelope with a password, for performance reasons, only a certain subkey is decrypted, exactly the one that is required to decrypt the message.

This is changed now in Mailvelope as all subkeys are decrypted by OpenPGP.js. Therefore there should be no more issues with messages encrypted for all subkeys of a public key.

**Closed by toberndo** 2019-03-11 14:37 UTC

**Comment by duraiarasan-1229** [comment] 2020-10-21 10:49
Hi Team, 

is anyone faced the below issue when decrypting the PGP file.

gpg: mdc_packet with invalid encoding

gpg: decryption failed: invalid packet

can anyone please let me know where the issue is?

what steps need to be followed to solve the issue.

Thanks
D
