### ISSUE TITLE
Google Inbox support

### ISSUE THREAD

**Issue by mikemol** [mailvelope/mailvelope#419] opened 2016-08-23 16:52 UTC
While GMail seems to be supported, Google Inbox does not. It would be very helpful to have this rectified.

**Comment by SonofLiberty90** [comment] 2016-09-02 09:59
Can confirm this.

**Comment by jgoclawski** [comment] 2016-10-10 21:17
Looks like a duplicate of #241. BTW: It mostly works OK, but you have to add it as a provider manually.

**Comment by toberndo** [comment] 2016-10-14 14:00
See: https://github.com/mailvelope/mailvelope/issues/241#issuecomment-253807614

**Closed by toberndo** 2016-10-14 14:00 UTC
