### ISSUE TITLE
Mailvelope unable to import some keys other apps can

### ISSUE THREAD

**Issue by bungabunga** [mailvelope/mailvelope#365] opened 2015-12-26 09:22 UTC
Mailvelope unable to import some public keys that other apps can.

"Import Error. Unable to import one key due to exception: TypeError: b.users[d].userId is null"

The key:
https://gist.github.com/bungabunga/998452425bec3b9da1e0

**Comment by fujisan43** [comment] 2016-03-22 10:45
Hello,
I have the same error when trying to import my secret keys in Firefox 45. I do not have the problem with google chrome though.

**Comment by fujisan43** [comment] 2016-03-22 15:37
If you have an ID that does not have an email address, this can be the cause of this error message.
So, just create a new uid (gpg2 --edit-key KEYID) and add  real name and email address. Select id without email and delete it, then save.
Export your keys and import them in mailvelope.

**Comment by toberndo** [comment] 2016-12-10 07:30
openpgpjs/openpgpjs#282 is closed, closing this as well.

**Closed by toberndo** 2016-12-10 07:30 UTC
