### ISSUE TITLE
Allow public key fetching from server

### ISSUE THREAD

**Issue by roobre** [mailvelope/mailvelope#149] opened 2013-11-24 19:46 UTC
It's a pain requesting each contact to provide its public key, either via plain text message, or an attachment.
The extension could automatically query a keyserver for a public key if an email arrives from a non-registered address.
If this is too complicated, allowing the user to manually search the keyserver for the desired email addres would also be a nice idea.

**Comment by hendrixski** [comment] 2015-06-03 22:57
I'm just gonna update this because I recently tried keybase.  HELLS YEAH!  If someone signs up and wants to send emails to me@address.com and rather than copy/paste a key just search my name and get all that info from keybase. Epic win.

**Comment by tanx** [comment] 2015-12-10 10:21
Started work on this. See here https://github.com/mailvelope/mailvelope/issues/319#issuecomment-163566340

Closing this issue since it's a duplicate of https://github.com/mailvelope/mailvelope/issues/319

**Closed by tanx** 2015-12-10 10:21 UTC

**Comment by dashohoxha** [comment] 2016-01-12 10:54
I don't think this is duplicate of #319. Only the second part of it is a duplicate: "manually search the keyserver for the desired email addres".

What about the first part: "automatically query a keyserver for a public key if an email arrives from a non-registered address"?

This is useful in case of checking signatures. In case you get a signed email from somebody that you don't know, at least you could check the signature and verify that the message is not tampered and that it is comming from a certain email address (which you don't know). In my opinion this is important.

**Comment by Steffeng5** [comment] 2016-08-11 10:42
Now both are closed. Is this still on the roadmap?
