### ISSUE TITLE
Add support for encrypted messages from facebook

### ISSUE THREAD

**Issue by MaxRink** [mailvelope/mailvelope#324] opened 2015-07-13 22:12 UTC
Facebook uses .asc files instead of inline messages.

**Comment by Manouchehri** [comment] 2015-09-04 17:17
Encrypted messages from Facebook work fine for me with Gmail. What provider are you with?

```
To: David Manouchehri <*snip>
Subject: Encrypted Notification from Facebook [*snip]
X-Priority: 3
X-Mailer: ZuckMail [version 1.00]
Return-Path: noreply@facebookmail.com
From: Facebook <noreply@facebookmail.com>
Message-ID: <*snip@www.facebook.com>
MIME-Version: 1.0
Content-Type: multipart/encrypted;
	boundary="*snip";
	protocol="application/pgp-encrypted";


This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--*snip
Content-Type: application/pgp-encrypted; charset="UTF-8"
Content-Transfer-Encoding: 7bit

Content-Description: PGP/MIME Versions Identification

Version: 1

--*snip
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Transfer-Encoding: 7bit
Content-ID: <0>
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----

*snip
-----END PGP MESSAGE-----


--*snip--
```

**Comment by MaxRink** [comment] 2015-09-04 21:25
Also google, but inbox instead of gmail.

**Comment by Br3ach** [comment] 2015-09-16 21:02
Same here. Always fails for FB e-mails with: Error! Error decrypting message!

That's on Gmail.

**Comment by Manouchehri** [comment] 2015-09-16 21:26
What browser? I'm not able to replicate the issue here with Chromium.

**Comment by Br3ach** [comment] 2015-09-16 21:46
Chrome 45 on Windows 10.

**Comment by Manouchehri** [comment] 2015-09-16 21:47
What other extensions/plugins do you have installed?

**Comment by Manouchehri** [comment] 2015-09-17 04:31
I doubt this it, but get [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) with all the rules added and [HTTPS Everywhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=en).

I'm using that setup with is Chromium 45.0.2454.85 (64-bit).

**Comment by Manouchehri** [comment] 2015-09-17 05:29
Oh, I missed the part where you said you were using Google Inbox and not Gmail.

This sounds like a duplicate of #241 then.

**Comment by Br3ach** [comment] 2015-09-17 06:45
Well, I'm using Gmail. Here's a video of the issue:
https://dl.dropboxusercontent.com/u/28406605/1.avi

Extensions are: Google Docs, Google Docs Offline, Google Mail Checker, Logitech Smooth Scrolling, Mailvelope, Hola, User-Agent Switcher. Tried disabling all of them - same issue.

**Comment by eltuctuc** [comment] 2015-09-17 06:51
AVI is fine, but I can't open it on my mac :-( Can you convert it in MPG?

**Comment by Br3ach** [comment] 2015-09-17 06:55
Here's a mov version:
https://dl.dropboxusercontent.com/u/28406605/1.mov

**Comment by toberndo** [comment] 2016-12-10 06:56
Inbox is now supported with v1.6.0. When the armored block is displayed as an attachment remains generally a problem.

**Closed by toberndo** 2016-12-10 06:56 UTC
