### ISSUE TITLE
Support keys on hardware tokens (enhancement)

### ISSUE THREAD

**Issue by mouse07410** [mailvelope/mailvelope#420] opened 2016-09-02 03:07 UTC
All the popular browsers (Chrome, Firefox, Safari) can use keys stored on hardware cryptographic tokens (smart cards), accessing them via PKCS#11 modules (Firefox) or through the OS (Chrome and Safari).

It would be great if Mailvelope could upload my public key (X.509 or OpenPGP) and perform crypto operations with the private key(s) on the token (via PKCS#11). 

That's how I use OpenPGP and S/MIME in Apple Mail (and MS Outlook :), and that's how I access protected Web sites via all of the aforementioned browsers. Extending use of hardware tokens to webmail would be stellar.

**Comment by jas4711** [comment] 2016-09-24 17:50
This looks like a duplicate of #238. Note that the PKCS#11 interface of Chrome/Firefox is not (to my knowledge) exposed through JavaScript.

**Comment by runasand** [comment] 2016-10-07 14:50
See also #343 and #432 for existing tickets requesting this feature.

**Comment by toberndo** [comment] 2017-03-20 11:40
Closing as duplicate of #238

**Closed by toberndo** 2017-03-20 11:40 UTC
