### ISSUE TITLE
Support for Google Inbox

### ISSUE THREAD

**Issue by toberndo** [mailvelope/mailvelope#241] opened 2014-11-10 16:59 UTC
Add support for Google Inbox

**Comment by simmac** [comment] 2015-03-08 14:35
@kevthehermit I can't get it to work in inbox. Can you explain how you fixed this?

**Comment by kevthehermit** [comment] 2015-03-08 14:53
Here is a screen of my Mail Provider settings for inbox

![inbox](https://cloud.githubusercontent.com/assets/2545096/6546198/cd5cc4b8-c5a2-11e4-8938-0d980d15b5c7.png)

**Comment by simmac** [comment] 2015-03-08 15:52
@kevthehermit Thank you, I had exactly the same settings, after deleting and readding them it works now!

**Comment by inequation** [comment] 2015-03-24 17:54
Two requests for Inbox support:

* ability for in-line editing – now one has to pop out the response window in order for the Mailvelope pop-up to appear,
* if replying, it would be nice to have the "transfer" button not replace all the contents of the message, but just the reply – i.e. I'd like to leave the preceding conversation intact.

The latter is possible by some careful copying & pasting, but it'd be nice to be able to do that automatically.

**Comment by Manouchehri** [comment] 2015-06-03 05:25
Same issue here, though I find the transfer feature works perfectly.

Unable to decrypt any messages, which is a bit disappointing.

**Comment by NickGeek** [comment] 2015-06-07 10:23
Decrypting is broken due to the reply system on Inbox (Mailvelope doesn't read the header)

**Comment by rengers** [comment] 2015-06-29 14:45
Yeah I have the same issue when trying to decrypt in inbox.  I get an error like:
"Error! Could not read this encrypted message: Error: Unknown ASCII armor type"

**Comment by Jamamuuga** [comment] 2015-07-11 04:24
+1 I also get the error message: "Error! Could not read this encrypted message: Error: Unknown ASCII armor type"

**Comment by Stephen304** [comment] 2015-09-25 18:41
Looking at the message source for an encryped facebook email reveals that it actually doesn't have encrypted.asc as an attachment, but uses multipart and `Content-Type: application/pgp-encrypted` as well as `Content-Type: application/octet-stream` and `Content-Disposition: inline; filename="encrypted.asc"`.

In theory, the browser is supposed to try to render the contents of encrypted.asc and fall back to an attachment. It might be that mailvelope needs to register itself as a handler for application/pgp-encrypted, but I don't know much about how that works. 

Point being, it seems like facebook might be following best practices and inbox and/or mailvelope needs support for this way of sending pgp, which looks like it falls back to an attached .asc file when not supported.

**Comment by JohanSpaedtke** [comment] 2016-04-01 09:14
+1 on the above
It would be nice if you could decrypt replies written by someone using mailvelope as Jamamuuga said and it would also be nice if mailvelope supported emails with the encrypted parts as attachments which would make it possible to use it together with many more PGP/GPG-email solutions

**Comment by niggo372** [comment] 2016-04-05 15:44
+1. This would be very helpful.

**Comment by stephen304** [comment] 2016-04-05 15:58
Instead of replying, if you just want to show support for this, you can use GitHub's new reactions feature to +1 the original post.

**Comment by cristian04** [comment] 2016-04-07 22:27
+1

**Comment by mlmurray** [comment] 2016-08-18 19:41
+1

**Comment by Abraxos** [comment] 2016-09-14 19:19
+1

**Comment by toberndo** [comment] 2016-10-14 14:00
Bug with message decryption in Inbox is now fixed in dev branch and also inbox.google.com will be active by default in the list of mail providers.
Nightlies available here: https://build.mailvelope.com/nightly/
New release available within two weeks.

**Comment by jgoclawski** [comment] 2016-10-17 20:34
I've checked the nightly and the bug is fixed and inbox is added as a provider, thanks!

But there's another issue: I can decrypt messages in the "Inbox", but not when I display messages as search results. The "key cursor" doesn't appear there. Actually, it does appear sometimes, in a non-deterministic way, seems random. It does appear when I select "show source". (it's not a regression, it's the same behavior as in 1.5.2).

Another thing: Is there any chance to load the plugin in quick reply box just like in Gmail? It would allow for easy replies.
Right now we need to pop out the response window, cut the original thread to clipboard, generate encrypted response and paste back the thread below. It's the only way to respond and not corrupt previous messages.

Should I open another issue for this?

**Comment by Whoknowsit** [comment] 2016-11-23 04:06
I'm trying to read mails, which have been sent via Thunderbird on Mac (using Enigmail). Encryption is set to PGP/MIME. When receiving the mail in Inbox, there's a file attached (encrypted.asc), which contains the actual encrypted mail. However, Mailvelope doesn't recognize it and doesn't offer to decrypt the mail. To decrypt the mail, i have to view the mail source ("Show original") where the attached file is embedded as plaintext. Then, Mailvelope offers me to decrypt the mail.

Alternatively, i have to send it as Inline-PGP, but Mailvelope may fail to decrypt it, if it's sent as HTML mail.

**Comment by toberndo** [comment] 2016-12-10 06:55
@jgoclawski 
> But there's another issue with Google Inbox: I can decrypt messages in the "Inbox", but not when I display messages as search results.

This issue is tracked with #30 

> Another thing: Is there any chance to load the plugin in quick reply box just like in Gmail? It would allow for easy replies.

Mailvelope currently only displays the icon if text box has certain minimum height. A work around that worked for me was to hit several times enter, the text box enlarges and the icon appears. Certainly not a good solution though.

**Comment by Redsandro** [comment] 2017-03-13 05:35
I can see that inbox is a provider listed in the mail.google.com options automatically after installing this extension. But it's not working for me. I just see this:

![image](https://cloud.githubusercontent.com/assets/1702193/23842752/dc3a982c-07b6-11e7-9dcb-cacd464431d8.png)

In gmail, the same emails are detected by Mailvelope fine.

I'm new to Mailvelope, just installed it now. I went to google to see if I made a mistake, and ended up in this issue. Looks like it's supposed to work now. Am I wrong? Or did this break recently?

I'm running Chrome 58.0.3029.14 on Linux.

**Comment by amitkot** [comment] 2017-09-27 09:38
I also can't get it to work on Google Inbox. Is there a way to reopen this issue?

**Comment by patrick-radulian** [comment] 2017-09-29 17:33
While it is, admittedly, very inconvenient, there is a relatively easy work-around for now.
When you view your email, you can click on the verical ellipsis icon on the top right corner, next to the time, as shown here:

![screenshot](https://user-images.githubusercontent.com/12211606/31028081-eb16c3d2-a54c-11e7-96af-8a6f9990a044.png)

Then click on "show original" and the email will open in a separate tab, which shows you the actual content. Then Mailvelope will detect it and offer to decrypt.

**Comment by ShawnTalbert** [comment] 2018-03-09 22:08
@patrick-radulian nice workaround for reading, but on that 'show original' page there's no option to reply, making it more awkward for writing a response. Since this issues has been here for over 3 years, perhaps it's time to give up on Mailvelope?

**Comment by Redsandro** [comment] 2018-11-02 20:03
Checking back to see if Mailvelope can enhance my `inbox.google.com` with security. Guess not.

Did anyone try FlowCrypt? It supports Inbox.

**Comment by yougotborked** [comment] 2018-11-02 20:38
Inbox is being depreciated on March 2019, so I would suggest closing this as wontfix. I've allready switched back to gmail.

**Closed** 2018-11-03 08:05 UTC
