### ISSUE TITLE
PGP/MIME decryption error:  Document not defined.

### ISSUE THREAD

**Issue by StanAccy** [mailvelope/mailvelope#225] opened 2014-09-11 16:22 UTC
Gmail, Chrome, Mac OS X
I received an encrypted email that contained a file attachment.  The plugin didnt recognize the PGP email until I clicked on "[Message Clipped] View Entire Message".  Once i expanded the email in to a separate window, the plugin highlighted the PGP message with the light yellow box.  After entering the key password, I got an error stating: Error! Document not defined.

**Comment by jo-tud** [comment] 2015-01-13 08:35
I received an OpenPGP/MIME message and the error when decrypting is also "Error! Document not defined." Even if OpenPGP/MIME is not supported it could be detected in the E-Mail-Header and the error could be more meaningfull. Additionally the text part could be decrypted and only binary parts discarded.

**Comment by pfctdayelise** [comment] 2015-07-11 14:00
Gmail with Mailvelope 0.12.1, Firefox 39.0, Ubuntu 14.04

I received an encrypted email with a file atachment and after clicking "View entire message" Mailvelope was able to decrypt it successfully. It showed a link to the attachment and the right filename in the tooltip.
However left-clicking does nothing, and right-clicking and choosing Save File As gives a file with a name like UvA0kiAF.bin . This is a bit disconcerting - it would be much nicer if the original filename was preserved, or at the very least, the correct file extension.

![mailvelope](https://cloud.githubusercontent.com/assets/360499/8633969/6e3198e2-27e5-11e5-95c7-f461f8e8f201.png)

**Comment by guillaume-uH57J9** [comment] 2015-11-26 19:14
Mailvelope 1.2.3, Firefox 38, Debian testing

I observe the same behavior as @pfctdayelise

**Comment by toberndo** [comment] 2016-12-06 15:46
This is a mixture of several problems and I would like to focus in this issue solely on the "document not defined" error when decrypting a PGP/MIME, which I'm not able to reproduce at the moment.
 
Once you have the PGP/MIME body displayed in the browser, Mailvelope is able to decrypt (text and attachment. The question is how deep we want to integrate with the mail client in the non-API variant of Mailvelope. We could automatically trigger to open a new tab with the RAW message, but experience with the Outlook.com integration show that things get messy if you do too much "magic". In the end it's an UI we are interfacing with and not an API.

> and right-clicking and choosing Save File As gives a file with a name like UvA0kiAF.bin 

This should be fixed.

**Closed** 2019-03-11 14:50 UTC
