### ISSUE TITLE
  // , Private Keys Keep Disappearing

### ISSUE THREAD

**Issue by v6** [mailvelope/mailvelope#321] opened 2015-06-06 03:04 UTC
// , 

```
➜  ~  uname -a
Linux nathan 3.16.0-39-generic #53-Ubuntu SMP Tue May 26 09:38:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
➜  ~  firefox --version
(process:14986): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Mozilla Firefox 38.0
➜  ~  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:    14.10
Codename:   utopic
```

Every time I import a set of keys, when I restart my computer, they aren't there anymore! 

This affects public keys, too. 

How can I fix this extremely frustrating problem? 

What avenues of investigation can I pursue to help debug? 

Can I contribute to the source code if we agree upon a specification for a bug fix?

**Comment by v6** [comment] 2015-07-19 08:32
// , Incidentally, this also applies to public keys, and just occurred again, not a few days ago.

**Comment by toberndo** [comment] 2015-07-20 08:15
Probably related to https://github.com/mailvelope/mailvelope/issues/304 there is no fix as of now.

**Comment by toberndo** [comment] 2016-12-10 06:27
Duplicate of #304. Closing.

**Closed by toberndo** 2016-12-10 06:27 UTC
