### ISSUE TITLE
Mailvelope displays only first text-part, swallows others

### ISSUE THREAD

**Issue by duckdalbe** [mailvelope/mailvelope#515] opened 2017-05-16 19:54 UTC
Mailvelope (in API-mode) displays only the first "inline"-disposited text/plain-part and swallows all others, regardless of nesting. It looks like there were no more content, event though there is.

(Parts with disposition "attachment" are listed on top as expected.)

**Comment by toberndo** [comment] 2017-05-17 13:33
Closing as duplicate of https://github.com/mailvelope/mailvelope/issues/516

**Closed by toberndo** 2017-05-17 13:33 UTC
